Changed door protocol to start passing information in environment variables. This also required adding the ability to pass environment variables to be set to the ExtSession routines. Also added zork, even though it isn't ready yet.

diff --git a/src/bbs/doors/adventure b/src/bbs/doors/adventure
--- a/src/bbs/doors/adventure
+++ b/src/bbs/doors/adventure
@@ -1,9 +1,11 @@
 #!/bin/sh
 ADVENTURE_PROG=/usr/local/bin/adventure
 
-BBS_DIR=$1
-BBS_USER=$2
-
+if [ "$BBS_DIR" == "" -o "$BBS_USER" == "" ];
+  echo "Missing BBS envionment variables"
+  exit 1
+fi
+  
 SAVEDIR=${BBS_DIR}/doors/data/adventure
 USER_SAVE=${SAVEDIR}/${BBS_USER}
 
